### ISSUE TITLE
Anti-spam solution

### ISSUE THREAD

**Issue by engram-design** [engram-design/Comments#12]
I'd like to start a discussion about anti-spam - because we love it so much :)

But seriously, we're wanting to put in the best anti-spam solutions around. Feel free to add your suggestions - be they methods to implement, or even third-party solutions.

We're looking at integrating with [craft.spamguard](https://github.com/selvinortiz/craft.spamguard), [Snaptcha](https://craftpl.us/plugins/snaptcha) and [Invisible Captcha](http://sprout.barrelstrengthdesign.com/craft-plugins/invisible-captcha). We may also incorporate some of these methods directly into the plugin.

Discuss!

**Comment by selvinortiz** [comment]
@engram-design Do you plan on integrating any type of flagging along with anti-spam measures?

Spam Guard has the ability to log all submissions to minimize the risk of false/positives but this seems like a feature that core can provide if at all desired.

There are two battles to fight, one against robots (direct submissions, headless browsers, etc) and the other against human spam.

Robot spam can be reduced by doing a few things...

1. Adding a honeypot field (not very effective on it's own)
2. Making sure javascript is required
3. Timing form rendering and form submission
4. Running some sort of user agent and IP validation

I see this as something that core could provide as its basic anti-spam measure or use **Invisible Captcha** since it is open source. **Snaptcha** as pointed out, is another solid option for fighting robot spam.

Human spam on the other hand is a little more advanced, in this cases the options are to...

1. Have a review/approval process (can get tedious)
2. Use a third party service like **Akismet**

This is something that **Spam Guard** could provide and bake into core eventually if it makes sense.

These comments are largely based on personal experience and observations, I'm not a Spam expert by any means.

**Comment by engram-design** [comment]
Awesome comments Selvin! I've already got some basic flagging functionality in the plugin, which is a good start. This allows users to flag inappropriate content, and if the flag limit is set low enough, it can easily be hidden quickly. You can also choose to moderate all comments before being publicly available.

I would be really interested in integrating Invisible Captcha, or a similar setup. This will likely be something built-in though, as I don't want to rely on other plugins for these sort of simple methods.

Then, as an option, I'd integrate Akismet (through Spam Guard) as more of an add-on option.

Again - great summary!

**Comment by engram-design** [comment]
Closed for now. Most of the functionality from Invisible Captcha is built-in. Will discuss Spam Guard integration with @selvinortiz for pre-1.0 release.
