### ISSUE TITLE
User with permissions cannot save security settings?

### ISSUE THREAD

**Issue by themccallister** [engram-design/Comments#27]
I am using this on a current project and its been great, ran into an issue today that I feel may be a simple fix... 

I granted a user group permissions to the Comments plugin:

https://www.dropbox.com/s/q76rje9psg464nx/Screenshot%202015-08-03%2017.33.07.png?dl=0

However, when the user is logged in and enters new words in `admin/comments/settings > security` they are unable to save new data in comment moderation:

https://www.dropbox.com/s/mq38v2rnx2fai4d/Screenshot%202015-08-03%2017.31.04.png?dl=0

Any direction on how to proceed with fixing this, I thought adding the permissions on the user settings would allow the user to save the plugin settings?

**Comment by engram-design** [comment]
@themccallister Ah, thats an interesting one! Only admin users can save plugin settings (among any other settings-based function), which is why its throwing the permission error. In fact, logged in as this use, you won't be able to access anything under Settings. All of those settings are settings of the plugin.

One way around this is to roll these settings into their own model/record, which is something I might do to get around this. You could also have two permission settings - one for general access, and one for editing the settings.

Interestingly, you shouldn't even be able to access the Settings page without being an Admin - is this something that you've removed out in [settings/index.html](https://github.com/engram-design/Comments/blob/master/comments/templates/settings/index.html#L1)?

**Comment by themccallister** [comment]
I did modify this and its Craft's native behavior. I'm going to close this ticket out.
