### ISSUE TITLE
Undefined property: stdClass::<property> when retrofitting comments field to existing entry without resaving

### ISSUE THREAD

**Issue by alecritson** [engram-design/Comments#30]
Hey,

This plugin is exactly what I need with a project at the moment and its really awesome, so thanks!

I ran into an issue though when installing this to an already existing site, heres how it goes:

- I installed comments
- Created `comments` a new field and attached it to a section
- I go to my entry template and put the form code in
- Submit a comment

Then I got this error:

```
Undefined property: stdClass::$requireModeration
```
So it looks like because I haven't saved the entry with the field, it doesn't have the required attributes set in order to do the checks. When I dump `$fieldSettings` it looks like this:

```php
stdClass#1
(
    [allowAnonymousGlobal] => ''
    [requireModerationGlobal] => '1'
    [commentsClosedGlobal] => ''
    [userPermissionsGlobal] => array
    (
        '*' => '1'
        1 => ''
    )
)
```

So it has the globals in there but not the individual settings, since you only check for `$fieldSettings->requireModeration` not `$fieldSettings->requireModerationGlobal`, but because of the `Global` bit at the end, when you do the merge in `Comments_SettingsService.php` it doesn't match.

I hope i'm making sense :)

So i've come up with a fix and will send a pull request if you are interested, or if you have a different solution thats fine too, but this worked for me and the plugin works without issue :)

Thanks again, this is awesome!

**Comment by engram-design** [comment]
Hey @alecritson thats an excellent point and something I hadn't tested yet, so thanks! I've actually been rethinking the whole field idea, so would be keen to get your feedback/thoughts on that. Its basically so you can control commenting per-element, but I think it can be done better...

**Comment by alecritson** [comment]
Nice one! glad it helped out :smile:

I quite like the way it is to be honest, I mean, when you add the field you get a list of global options for it which would cascade into all the entries, then you can fine tune them for each entry if you need to, seems like a nice way to do it.

Did you have any ideas of how you wanted to do it?

Off the top of my head, it could be cool to define "rule sets" in the comments settings and when you add a field you can either choose a ruleset or inputs it already comes with? That way you could have tons of elements using the same rulesets if needed but then also elements with their own. Changing a ruleset would cascade onto any fields with that set selected..... just a thought :smile:

**Comment by engram-design** [comment]
Yeah, thats pretty much along the lines of what I was thinking. Using Entries as an example element, for each section, you'd have the option to either turn off/on comments. This allows new entries to allow comments, but also allows you to 'shut off' comments for an entire section.

Then, for the case of you want to either a) enable commenting for a selection of entries only, or b) disable commenting for a selection of entries only, you'd have a nice interface (essentially a table) where you could flick on/off commenting in bulk.

So really, it all comes down to consolidating settings, rather than have them scattered. Then again, the way its working now seems fine for the moment, so in the short term, I'll leave it at that :smiley:

**Comment by engram-design** [comment]
@alecritson The [0.3.8](https://github.com/engram-design/Comments/releases/tag/0.3.8) release properly fixes this issue. I'm also going to retire the Comments fieldtype, in favour of a centralised permissions system. Mostly because its a little hard to keep track of settings for sections, and keeping a number of unnecessary fields around.
