### ISSUE TITLE
Clarification request: Comments plugin on Craft Personal/Client

### ISSUE THREAD

**Issue by Rocketpilot** [engram-design/Comments#35]
The docs doesn't make this very clear, but I did assume the Comments plugin would only really work on Craft Pro as it's the only version that allows more than two users to be created in a single install. But this change-log entry made me wonder:

`Ensure works well on Craft Client/Craft Personal.` 

So can it be used in production on Craft Client? I recall trying a while back with no luck.

**Comment by engram-design** [comment]
The aim is to work on any Craft version, because you can have guest comments. If you choose to turn that off, then yes, you'll have a very quiet comments section on your site :smiley: 

I'm working through some updates to the plugin now, so this will be confirmed in the next release. However, I've yet to come across any issues so far.

**Comment by Rocketpilot** [comment]
I finally had a chance to try this out and yes, it works brilliantly. I think I'd only ask that the docs are a bit clearer about how it works in the Personal version.

**Comment by engram-design** [comment]
Agreed - the docs need a bit of work in general, I'll add a clarification. Thanks!
