### ISSUE TITLE
onSaveComment not passing the comment

### ISSUE THREAD

**Issue by bkmorse** [engram-design/Comments#39]
I used the example code from your wiki:

```
craft()->on('comments.onSaveComment', function($event) {
	$comment = $event->params['comment'];
	print $comment;
});
```

It returns nothing.

If I do a var_dump($event), I see the comment but in a private object.

**Comment by engram-design** [comment]
I'm not 100% sure on this one, mainly because I don't use `print`, but that function seems to mimick php's `echo` function, where it only prints variables, and not objects/arrays.

You'd be better off using `var_dump($comment)` or `print_r($comment)` and it should return a CommentModel.

Can you confirm this? I can confirm `print $comment;` indeed returns nothing for me, but `var_dump($comment)` does.

**Comment by bkmorse** [comment]
var_dump does, but the example you provide in your wiki (https://github.com/engram-design/Comments/wiki/Events-Reference: onSaveComment), to get the comment from the event, returns nothing. What is the proper way to get the comment from your example?

**Comment by engram-design** [comment]
For future reference, the example returns a [CommentModel](https://github.com/engram-design/Comments/wiki/Comment-Model), so you'd access attributes via `$comment->comment`, etc.

**Comment by madebyshape** [comment]
I'm trying to access the CommentModel, but clicking any link to this just asks me to create a new page on Github?! Did it get removed?

**Comment by bkmorse** [comment]
`$comment = $event->params['comment'];`

**Comment by engram-design** [comment]
@madebyshape Sorry about that, what happens what I renamed doc page. Link updated, but also via https://github.com/engram-design/Comments/wiki/09.-Comment-Model for Comment Model information, and https://github.com/engram-design/Comments/wiki/13.-Events-Reference for Events References
