### ISSUE TITLE
Template Error on Permissions Tab

### ISSUE THREAD

**Issue by joedakroub** [engram-design/Comments#45]
Clicking the Permissions tab for the Comments plugin displays:

<img width="1363" alt="screen shot 2016-07-19 at 8 51 14 pm" src="https://cloud.githubusercontent.com/assets/9915596/16971543/c8347b82-4df2-11e6-9afd-28ca64cac61c.png">

I am running **Craft 2.6.2797**.

**Comment by engram-design** [comment]
Thanks for reporting, will fix in the next release.

**Comment by chadcrowell** [comment]
I have this problem as well, though it appears a little differently.

![screen shot on 2016-07-27 at 13-22-02](https://cloud.githubusercontent.com/assets/48151/17194677/08628c8c-540e-11e6-8eac-6fc0d8350fbd.png)

**Comment by aelvan** [comment]
Same error as @joedakroub here.

**Comment by engram-design** [comment]
This is fixed in [0.4.5](https://github.com/engram-design/Comments/releases/tag/0.4.5).

**Comment by chadcrowell** [comment]
I am getting this exact error again in 0.4.7.

**Comment by engram-design** [comment]
@chadcrowell Is it the exact same error you posted previously `Impossible to access a key ("AdWizard_Ad")` on a null variable?

**Comment by chadcrowell** [comment]
Hi Josh, thanks for the help. We dropped Comments back down to the previous
version we were using in order to get things working again and haven’t had
a chance to do the upgrade again. We’re in the final stretch on this
project so we’ll definitely get the upgrade back in place sometime soon.
The error was the same one you referenced, however. I’ll let you know
if/when we hit the issue again.
